


DEFAULT_N_DIMENSIONS = 2;
DEFAULT_N_DATAPOINTS = 2000;
DEFAULT_SEED = 1;
DEFAULT_N_OUTLIERS = 50;
DEFAULT_N_CLUSTERS = 5;
DEFAULT_CLUSTER_MASS = [];
DEFAULT_MINIMUM_CLUSTER_MASS = 0;
DEFAULT_DISTRIBUTION = 0;
DEFAULT_DISTRIBUTION_FLAG = 1;
DEFAULT_MULTIVARIATE = 0;
DEFAULT_ROTATION = 0;
DEFAULT_CORRELATION = 0;
DEFAULT_COMPACTNESS = 0.1;
DEFAULT_ALPHA = 0;
DEFAULT_ALPHA_FACTOR = 1;
DEFAULT_SCALE = 1;
DEFAULT_NOISE = 0;
DEFAULT_VALIDITY_SILHOUETTE = 0;
DEFAULT_VALIDITY_GINDICES = 0;